// <auto-generated />
using MedicineApp.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicineApp.Migrations
{
    [DbContext(typeof(MedicineContext))]
    [Migration("20231016192822_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicineApp.Entities.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineId"));

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MedicineType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("MedicineId");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            MedicineId = 1,
                            MedicineName = "Tylenol",
                            MedicineType = "Flu and Fever",
                            Price = 10.0m,
                            StockQuantity = 100
                        },
                        new
                        {
                            MedicineId = 2,
                            MedicineName = "Advil",
                            MedicineType = "Headaches",
                            Price = 13.0m,
                            StockQuantity = 29
                        },
                        new
                        {
                            MedicineId = 3,
                            MedicineName = "Xylel",
                            MedicineType = "Skin",
                            Price = 15.0m,
                            StockQuantity = 120
                        },
                        new
                        {
                            MedicineId = 4,
                            MedicineName = "CapB",
                            MedicineType = "Bones",
                            Price = 30.0m,
                            StockQuantity = 130
                        },
                        new
                        {
                            MedicineId = 5,
                            MedicineName = "Adderal",
                            MedicineType = "Stomach Pain",
                            Price = 12.0m,
                            StockQuantity = 340
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
